spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/usainua?currentSchema=public
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: false
    database: postgresql
    database-platform: postgresql
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.in.odessa@gmail.com
    password: xxfcmvzqnxtpaius
    properties:
      mail:
        smtp:
          auth: true
          connection-timeout: 5000
          timeout: 5000
          starttls:
            enable: true
        debug: false
server:
  port: 8081
logging:
  level:
    root: info
security:
  jwt:
    secret: 'U3BhY2VMYWI='

