name: Main branch testing & deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Step 1 - Checkout master branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          architecture: x64
          cache: maven

      - name: Step 3 - Build with Maven
        run: mvn -B package --file pom.xml

      - name: Step 4 - Check place of war file
        run: ls

      - name: Step 5 - Auto-deploy on Tomcat
        run: curl -v -u admin:32167 http://213.200.39.253:8080/manager/text/deploy?war=usainua_api-0.0.1-SNAPSHOT.war
