name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Step 1 - Checkout master branch from GitHub
      uses: actions/checkout@v3
    
    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
        architecture: x64
        cache: maven

    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml
